# Generated by Django 5.0.6 on 2024-05-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pelanggaran_Siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggaran',
            name='catatan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='poin',
            field=models.IntegerField(),
        ),
    ]
