# Generated by Django 5.0.6 on 2024-05-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pelanggaran_Siswa', '0002_alter_pelanggaran_catatan_alter_pelanggaran_poin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggarankategori',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pelanggaran_Siswa.sekolah'),
        ),
    ]
